- name: install packasges using loops
  hosts: web
  become: yes
  tasks: 
  - name: installing all packages
    ansible.builtin.dnf:
      name: "{{ item }}"
      state: latest
    loop:
    - mysql
    - nginx
    - postfix