- name: install packasges using loops
  hosts: localhost
  become: yes
  tasks: 
  - name: installing all packages
    ansible.builtin.dnf:
      name: {{ item }}
      state: latest
    loop:
    - mysql
    - nginx
    - postfix